{% set name = "lpython_emulation" %}
{% set version = "0.0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lpython_emulation-{{ version }}.tar.gz
  sha256: c7a23d99075e2e559f4d4c4fa0cf9ed2d08234f86f0e3c84632ae6bcd8c0189b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - lpython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Shaikh-Ubaid/lpython_packages
  summary: Package for adding type information to python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shaikh-Ubaid
